name: 张玉洁的组件版本一二三四五六七八九十版本一二三四五六七八九十一二1
description: 名称最长WWW WWW WWW WWW WWWFFF
keywords:
  - websocket
  - network
  - 1
license: aaa                                   # GPLv2，LGPLv2.1，MIT，Apache license v2.0，BSD

source_file:
  - src/*.c

build_config:
  include:
    - include
  cflag: ""                             # C 编译器所需要要的编译参数
  define:                                      # 宏定义
    - CONFIG_USING_TLS

install:
  - dest: include
    source:
      - "include/librws.h"
